apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websites-ssl
  annotations:
    kubernetes.io/ingress.global-static-ip-name: homepage-ipv4
spec:
  rules:
  - host: {{PRIMARY_DOMAIN}}
    http:
      paths:
      - backend:
          serviceName: homepage-deploy-service
          servicePort: 80
  - host: battlefleet.eu
    http:
      paths:
      - backend:
          serviceName: battlefleet-deploy-service
          servicePort: 80
  tls:
  - secretName: {{TLS_SECRET}}-tls
    hosts:
      - {{PRIMARY_DOMAIN}}
      - battlefleet.eu
