apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websites
  annotations:
    kubernetes.io/ingress.global-static-ip-name: globalhomepage
spec:
  rules:
  - host: ackerson.de
    http:
      paths:
      - backend:
          serviceName: homepage-deploy-service
          servicePort: 80
#  - host: battlefleet.online
#    http:
#      paths:
#      - backend:
#          serviceName: battlefleet-deploy-service
#          servicePort: 80
