apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websites
  annotations:
    kubernetes.io/ingress.global-static-ip-name: globalhomepage # found: https://console.cloud.google.com/networking/addresses/list?project=kubernetes-207013
    #ingress.gcp.kubernetes.io/pre-shared-cert: ackersonde-ssl
spec:
  tls:
    - secretName: ackerson-de-tls
      hosts:
        - ackerson.de
        #- battlefleet.online
  rules:
  - host: ackerson.de
    http:
      paths:
      - backend:
          serviceName: homepage-deploy-service
          servicePort: 80
#  - host: battlefleet.online
#    http:
#      paths:
#      - backend:
#          serviceName: battlefleet-deploy-service
#          servicePort: 80
